version: '3.8'
services:
  node:
    container_name: ${COMPOSE_PROJECT_NAME}-node
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './app:/app'
    ports:
      - '8080:8080'
